# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Antoine Dao
tagline: Aspiring Cloud Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'A passionate and inquisitive engineer working to bring desktop based building design into cloud infrastructures. Strong experience using/customising open source physics simulation tools to perform large scale parametric studies. Also have experience with Object Oriented Programming, Test Driven Development and cloud networking/management. Seeking to join start up or established company to deliver valuable insights via data analytics and advanced data-driven methods.'

#sidebar links
email: antoinedao1@gmail.com
#phone: 012 345 6789
#website: blog.webjeda.com #do not add http://
linkedin: antoinedao
github1: twanito
github2: AntoineDao
twitter: '@ntoinedao'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-109505825-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
